### ISSUE TITLE
sh.CommandNotFound: wmic

### ISSUE THREAD

**Issue by zhangjianpinghik** [kanzure/python-wmi-client-wrapper#14]
>>> output = wmic.query("SELECT * FROM Win32_Processor")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/wmi_client_wrapper/wrapper.py", line 111, in query
    output = sh.wmic(*arguments)
  File "/usr/local/lib/python3.4/dist-packages/sh.py", line 3349, in __getattr__
    return self.__env[name]
  File "/usr/local/lib/python3.4/dist-packages/sh.py", line 3226, in __getitem__
    raise CommandNotFound(k)
sh.CommandNotFound: wmic

**Comment by kanzure** [comment]
You'll need to install the windows management instrumentation stuff: https://docs.microsoft.com/en-us/windows/desktop/wmisdk/wmic

**Comment by zhangjianpinghik** [comment]
only the SELECT * FROM Win32_Processor is error .the other works well!

**Comment by djloot** [comment]
I got this running on a Raspberry Pi.  You don't necessarily need the Microsoft's stuff, you can use the ubuntu packages
