### ISSUE TITLE
error：output = wmic.query("SELECT * FROM Win32_ComputerSystem")

### ISSUE THREAD

**Issue by zhangjianpinghik** [kanzure/python-wmi-client-wrapper#15]
>>> output = wmic.query("SELECT * FROM Win32_ComputerSystem")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/wmi_client_wrapper/wrapper.py", line 98, in query
    return WmiClientWrapper._parse_wmic_output(output, delimiter=self.delimiter)
  File "/usr/local/lib/python2.7/dist-packages/wmi_client_wrapper/wrapper.py", line 137, in _parse_wmic_output
    moredata = list(csv.DictReader(strio, delimiter=delimiter))
  File "/usr/lib/python2.7/csv.py", line 108, in next
    row = self.reader.next()
_csv.Error: field larger than field limit (131072)

**Comment by zhangjianpinghik** [comment]
@kanzure  can you help me?
